apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
      - name: ghcr-auth
      containers:
      - name: worker
        image: ghcr.io/marcel/efg-nsu-portal:latest
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: ENABLE_API
          value: "false"
        - name: ENABLE_WHATSAPP
          value: "false"
        - name: ENABLE_SCHEDULER
          value: "true"
        envFrom:
        - secretRef:
            name: api-secrets
